### ISSUE TITLE
En el repositorio solo debe almacenarse código fuente

### ISSUE THREAD

**Issue by evolentini** [agumig/TSSE_18Co_GrossoA#1]
En el repositorio no se debe almacenar ni código binario ni archivos generados por herramientas automáticas, solo se debe almacenar código fuente. Por eso la carpeta `TP2/build` debe agregarse en el archivo `.gitignore` y eliminarse de repositorio.
@marianofino @rafaeloliva

**Comment by agumig** [comment]
Se incorporan las líneas TP2/build y TP3/build en archivo .gitignore y se eliminan del repositorio.
