### ISSUE TITLE
Se deben eliminar las constantes mágicas del código de producción

### ISSUE THREAD

**Issue by evolentini** [agumig/TSSE_18Co_GrossoA#2]
Se debe refactorizar el código de producción para eliminar las constantes numericas y reemplazarlas por constantes simbolicas.

https://github.com/agumig/TSSE_18Co_GrossoA/blob/5f60f782bef5cd977cf17a19b5dc212327471737/TP2/src/leds.c#L50
https://github.com/agumig/TSSE_18Co_GrossoA/blob/5f60f782bef5cd977cf17a19b5dc212327471737/TP2/src/leds.c#L55

@marianofino @rafaeloliva

**Comment by agumig** [comment]
Se corrige mediante constantes simbólicas:

https://github.com/agumig/TSSE_18Co_GrossoA/blob/a6519568f7790f9f4ac2f93590bd2873abd29428/TP2/src/leds.c#L7
https://github.com/agumig/TSSE_18Co_GrossoA/blob/a6519568f7790f9f4ac2f93590bd2873abd29428/TP2/src/leds.c#L8
https://github.com/agumig/TSSE_18Co_GrossoA/blob/a6519568f7790f9f4ac2f93590bd2873abd29428/TP2/src/leds.c#L51
https://github.com/agumig/TSSE_18Co_GrossoA/blob/a6519568f7790f9f4ac2f93590bd2873abd29428/TP2/src/leds.c#L56
