### ISSUE TITLE
Se debe refactorizar el código de producción para eliminar repeticiones

### ISSUE THREAD

**Issue by evolentini** [agumig/TSSE_18Co_GrossoA#3]
En esta línea 

https://github.com/agumig/TSSE_18Co_GrossoA/blob/5f60f782bef5cd977cf17a19b5dc212327471737/TP2/src/leds.c#L27

se debería llamar a la función `LedsTurnOffAll()` en lugar de repetir la asignación de valores a la variable. Aun cuando es muy poco código es una buena practica evitar repeticiones. En este caso incluso el requisito dice que los leds deben arrancar apagados, por lo que es totalmente lógico llamar a la función para apagar todos.

@marianofino @rafaeloliva

**Comment by agumig** [comment]
Se cambia línea de código por función:

https://github.com/agumig/TSSE_18Co_GrossoA/blob/11fe5f0e0c4ac147f23474fb42cf351d65294250/TP2/src/leds.c#L28
