### ISSUE TITLE
Se podría simplificar el código de la función

### ISSUE THREAD

**Issue by evolentini** [agumig/TSSE_18Co_GrossoA#4]
El código de la función

https://github.com/agumig/TSSE_18Co_GrossoA/blob/5f60f782bef5cd977cf17a19b5dc212327471737/TP2/src/leds.c#L40-L46

se podría reescribir como

```c
bool IsLedTurn(uint8_t led) 
{ 
     return (*Direccion & IndexToMask(led)) != SINGLE_LED_OFF;
} 
```

@marianofino @rafaeloliva

**Comment by agumig** [comment]
Se simplifica el código con lo recomendado.
