### ISSUE TITLE
Todas las funciones de la biblioteca deben tener un comportamiento uniforme

### ISSUE THREAD

**Issue by evolentini** [agumig/TSSE_18Co_GrossoA#5]
Si para la función `LedsTurnOnSingle()` se escribieron pruebas que controlan los valores limites de los parámetros y el rango de los parámetros, entonces para todas las otras funciones de la biblioteca deberían hacer lo mismo, en lo posible sin repetir código y centralizando el control en una función (o macro) interna.

https://github.com/agumig/TSSE_18Co_GrossoA/blob/5f60f782bef5cd977cf17a19b5dc212327471737/TP2/test/test_leds.c#L102-L120

@marianofino @rafaeloliva

**Comment by agumig** [comment]
Se incorporan las demás funciones (LedsTurnOffSingle() y IsLedTurn()) al test de valores límites:

https://github.com/agumig/TSSE_18Co_GrossoA/blob/70bd091694311579c235cd5dcc743750485a5996/TP2/test/test_leds.c#L99-L107
