### ISSUE TITLE
No es necesario prender y apagar un led para saber que esta apagado

### ISSUE THREAD

**Issue by evolentini** [agumig/TSSE_18Co_GrossoA#6]
Estas dos lineas

https://github.com/agumig/TSSE_18Co_GrossoA/blob/5f60f782bef5cd977cf17a19b5dc212327471737/TP2/test/test_leds.c#L80-L81

se pueden eliminar, ya hay un test anterior que garantiza que todos los leds arrancan apagados, no es necesario prender y apagar el led para consultar el estado de un led apagado.

@marianofino @rafaeloliva

**Comment by agumig** [comment]
Se simplifica el código utilizando la condición previa según se recomienda.

https://github.com/agumig/TSSE_18Co_GrossoA/blob/11fe5f0e0c4ac147f23474fb42cf351d65294250/TP2/test/test_leds.c#L70-L74
