### ISSUE TITLE
No se debe dejar código comentado en producción

### ISSUE THREAD

**Issue by evolentini** [agumig/TSSE_18Co_GrossoA#7]
El código que no se utiliza debería ser removido antes de enviarlo a producción. Tambien los comentarios debería ser acomodados para que ayuden a entender el código, o removidos si son solo anotaciones.

https://github.com/agumig/TSSE_18Co_GrossoA/blob/5f60f782bef5cd977cf17a19b5dc212327471737/TP2/test/test_leds.c#L24-L39

@marianofino @rafaeloliva

**Comment by agumig** [comment]
Se quita código no usado (comentado).
