### ISSUE TITLE
Debe utilizar un Mock para reemplazar `hw_pressure_port.c `

### ISSUE THREAD

**Issue by evolentini** [agumig/TSSE_18Co_GrossoA#8]
El archivo `hw_pressure_port.c` debe implementar las funciones de acceso físico al conversar AD. Lo correcto es que en lugar de reescribirlo con funciones ficticias se lo reemplace por un Mock creado con FFF o con CMock. En el contexto del problema FFF sería una opción más fácil de utilizar.

@marianofino @rafaeloliva

**Comment by agumig** [comment]
Se incorpora el uso de mock con FFF.

https://github.com/agumig/TSSE_18Co_GrossoA/blob/9db85cd94365ebecfc593edbd734aad05e50f6a9/TP3/test/test_sensor_presion.c#L13

https://github.com/agumig/TSSE_18Co_GrossoA/blob/9db85cd94365ebecfc593edbd734aad05e50f6a9/TP3/test/test_sensor_presion.c#L103
